version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  allowed_updates:
    - match:
        update_type: "security"
  open-pull-requests-limit: 10
